services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development # - Use the dev stage with Xdebug
    container_name: emr-app
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: electronic_medical_record
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - postgres
      - redis
    networks:
      - emr

  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development # <--- Keep consistent with app
    container_name: emr-horizon
    command: php artisan horizon
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    depends_on:
      - redis
      - app
    networks:
      - emr

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    container_name: emr-scheduler
    command: php artisan schedule:work
    volumes:
      - ./src:/var/www
    depends_on:
      - app
      - redis
    networks:
      - emr

  nginx:
    # Use standard alpine for dev to allow easy volume mounting
    image: nginx:alpine
    container_name: emr-nginx
    ports:
      - "80:80"
    volumes:
      - ./src/public:/var/www/public # Mount the public folder directly
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - emr

  postgres:
    image: postgres:16-alpine
    container_name: emr-postgres
    environment:
      POSTGRES_DB: electronic_medical_record
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d electronic_medical_record" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - emr

  redis:
    image: redis:alpine
    container_name: emr-redis
    ports:
      - "6379:6379"
    networks:
      - emr

networks:
  emr:

volumes:
  pgdata: