services:
  care-flow-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development # - Use the dev stage with Xdebug
    container_name: care-flow-app
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: care-flow-postgres
      DB_PORT: 5432
      DB_DATABASE: care_flow_system
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - care-flow-postgres
      - care-flow-redis
    networks:
      - care-flow

  care-flow-horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development # <--- Keep consistent with app
    container_name: care-flow-horizon
    command: php artisan horizon
    restart: always
    volumes:
      - ./src:/var/www
    depends_on:
      - care-flow-redis
      - care-flow-app
    networks:
      - care-flow

  care-flow-reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    container_name: care-flow-reverb
    restart: always
    working_dir: /var/www
    volumes:
        - ./src:/var/www
    # Reverb needs the env vars to know its keys/host
    env_file: ./src/.env
    # Map the Reverb port so your browser can connect
    ports:
      - "${VITE_REVERB_PORT:-8080}:8080"
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    networks:
      - care-flow
    depends_on:
      - care-flow-redis

  care-flow-scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    container_name: care-flow-scheduler
    command: php artisan schedule:work
    volumes:
      - ./src:/var/www
    depends_on:
      - care-flow-app
      - care-flow-redis
    networks:
      - care-flow

  care-flow-nginx:
    # Use standard alpine for dev to allow easy volume mounting
    image: nginx:alpine
    container_name: care-flow-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www # Mount the public folder directly
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - care-flow-app
      - care-flow-reverb
    networks:
      - care-flow

  care-flow-postgres:
    image: postgres:16-alpine
    container_name: care-flow-postgres
    environment:
      POSTGRES_DB: care_flow_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d care_flow_system" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - care-flow

  care-flow-redis:
    image: redis:alpine
    container_name: care-flow-redis
    ports:
      - "6379:6379"
    networks:
      - care-flow

networks:
  care-flow:

volumes:
  pgdata: