import {
    ChevronLeft,
    ChevronRight,
    LayoutDashboard,
    Stethoscope,
    Users,
    CalendarCheck,
    ClipboardList,
    Activity,
    FileText,
    Hospital,
    Wallet,
    Package,
    FilePlus,
    Syringe,
    Archive,
    Microscope,
    Clipboard,
    TestTube2,
    ScanLine,
    ReceiptText,
    CreditCard,
    Shield,
    UserCircle,
    Calendar,
    Building,
    MapPin,
    Settings,
    UserCog,
    Key,
    Puzzle,
    History,
    PillIcon,
    SettingsIcon, BarChart3, Briefcase, FolderPlus, Inbox, FileLock

} from "lucide-vue-next"

export const iconRegistry = {
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    "layout-dashboard": LayoutDashboard,
    "overview": LayoutDashboard,
    "stethoscope": Stethoscope,
    "users": Users,
    "calendar-check": CalendarCheck,
    "clipboard-list": ClipboardList,
    "activity": Activity,
    "file-text": FileText,
    "hospital": Hospital,
    "wallet": Wallet,
    "package": Package,
    "file-plus": FilePlus,
    "syringe": Syringe,
    "archive": Archive,
    "microscope": Microscope,
    "clipboard": Clipboard,
    "test-tube": TestTube2,
    "scanner": ScanLine,
    "file-invoice": ReceiptText,
    "credit-card": CreditCard,
    "shield": Shield,
    "user-circle": UserCircle,
    "calendar": Calendar,
    "building": Building,
    "map-pin": MapPin,
    "settings": Settings,
    "user-cog": UserCog,
    "key": Key,
    "puzzle": Puzzle,
    "history": History,
    "pill":PillIcon,
    "setting":SettingsIcon,
    "folder-plus":FolderPlus,
    "briefcase":Briefcase,
    "bar-chart-3":BarChart3,
    "inbox":Inbox,
    "file-clock":FileLock,



}

export const moduleIconMap = {
    dashboard:'layout-dashboard',
    registry: 'folder-plus',
    mydesk: 'briefcase',
    tracking: 'map-pin',
    organization: 'wallet',
    report: 'users',
    admin: 'settings',
}
